export const VERIFY_USER_SOLUTION = 'VERIFY_USER_SOLUTION';

export const USER_SOLUTION_RESULT = 'USER_SOLUTION_RESULT';

export const UPDATE_CURRENT_PUZZLE = 'UPDATE_CURRENT_PUZZLE';

export const UPDATE_CURRENT_ROUND_PHASE = 'UPDATE_CURRENT_ROUND_PHASE';

export const UPDATE_COUNTDOWN = 'UPDATE_COUNTDOWN';

export const UPDATE_PUZZLE_DATA = 'UPDATE_PUZZLE_DATA';

export const UPDATE_ROUND_REMAINING = 'UPDATE_ROUND_REMAINING';
