export const CURRENT_ROUND = 'CURRENT_ROUND';
export const ROUND_PHASE = 'ROUND_PHASE';
export const COUNTDOWN = 'COUNTDOWN';
export const PUZZLE = 'PUZZLE';
export const REMAINING = 'REMAINING';

export const SELECTED_ROUND = 'SELECTED_ROUND';
export const START_ROUND = 'START_ROUND';
export const STOP_ROUND = 'STOP_ROUND';

export const PARTICIPANT_SOLUTION = 'PARTICIPANT_SOLUTION';
export const SOLUTIONS_SYNC = 'SOLUTIONS_SYNC';
