export const SWITCH_VISIBLE_SCORE = 'SWITCH_VISIBLE_SCORE';
export const OPEN_PARTICIPANT_INPUT_POP_UP = 'OPEN_PARTICIPANT_INPUT_POP_UP';
export const CLOSE_PARTICIPANT_INPUT_POP_UP = 'CLOSE_PARTICIPANT_INPUT_POP_UP';
